// Code generated by protoc-gen-go.
// source: proto/checker.proto
// DO NOT EDIT!

/*
Package checker is a generated protocol buffer package.

It is generated from these files:
	proto/checker.proto

It has these top-level messages:
	Any
	Timestamp
	Target
	Check
	Header
	HttpCheck
	RDSCheck
	Metric
	RDSResponse
	HttpResponse
	CheckResourceResponse
	ResourceResponse
	CheckResourceRequest
	TestCheckRequest
	TestCheckResponse
	CheckResponse
	CheckResult
	DiscoveryEvent
*/
package checker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Any struct {
	TypeUrl string `protobuf:"bytes,1,opt,name=type_url" json:"type_url,omitempty"`
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Any) Reset()                    { *m = Any{} }
func (m *Any) String() string            { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()               {}
func (*Any) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Timestamp struct {
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanos   int64 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Target struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Check struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Interval  int32      `protobuf:"varint,2,opt,name=interval" json:"interval,omitempty"`
	Target    *Target    `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	LastRun   *Timestamp `protobuf:"bytes,4,opt,name=last_run" json:"last_run,omitempty"`
	CheckSpec *Any       `protobuf:"bytes,5,opt,name=check_spec" json:"check_spec,omitempty"`
	Name      string     `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
}

func (m *Check) Reset()                    { *m = Check{} }
func (m *Check) String() string            { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()               {}
func (*Check) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Check) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Check) GetLastRun() *Timestamp {
	if m != nil {
		return m.LastRun
	}
	return nil
}

func (m *Check) GetCheckSpec() *Any {
	if m != nil {
		return m.CheckSpec
	}
	return nil
}

type Header struct {
	Name   string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type HttpCheck struct {
	Name     string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Path     string    `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Protocol string    `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	Port     int32     `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Verb     string    `protobuf:"bytes,5,opt,name=verb" json:"verb,omitempty"`
	Headers  []*Header `protobuf:"bytes,6,rep,name=headers" json:"headers,omitempty"`
	Body     string    `protobuf:"bytes,7,opt,name=body" json:"body,omitempty"`
}

func (m *HttpCheck) Reset()                    { *m = HttpCheck{} }
func (m *HttpCheck) String() string            { return proto.CompactTextString(m) }
func (*HttpCheck) ProtoMessage()               {}
func (*HttpCheck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HttpCheck) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type RDSCheck struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Protocol    string `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	Username    string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Password    string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	Database    string `protobuf:"bytes,5,opt,name=database" json:"database,omitempty"`
	QueryString string `protobuf:"bytes,6,opt,name=query_string" json:"query_string,omitempty"`
}

func (m *RDSCheck) Reset()                    { *m = RDSCheck{} }
func (m *RDSCheck) String() string            { return proto.CompactTextString(m) }
func (*RDSCheck) ProtoMessage()               {}
func (*RDSCheck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Metric struct {
	Name  string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value float64  `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	Tags  []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RDSResponse struct {
	Rows string `protobuf:"bytes,1,opt,name=rows" json:"rows,omitempty"`
}

func (m *RDSResponse) Reset()                    { *m = RDSResponse{} }
func (m *RDSResponse) String() string            { return proto.CompactTextString(m) }
func (*RDSResponse) ProtoMessage()               {}
func (*RDSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type HttpResponse struct {
	Code    int32     `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Body    string    `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	Headers []*Header `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty"`
	Metrics []*Metric `protobuf:"bytes,4,rep,name=metrics" json:"metrics,omitempty"`
	Host    string    `protobuf:"bytes,5,opt,name=host" json:"host,omitempty"`
}

func (m *HttpResponse) Reset()                    { *m = HttpResponse{} }
func (m *HttpResponse) String() string            { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()               {}
func (*HttpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HttpResponse) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpResponse) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type CheckResourceResponse struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Check *Check `protobuf:"bytes,2,opt,name=check" json:"check,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *CheckResourceResponse) Reset()                    { *m = CheckResourceResponse{} }
func (m *CheckResourceResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckResourceResponse) ProtoMessage()               {}
func (*CheckResourceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CheckResourceResponse) GetCheck() *Check {
	if m != nil {
		return m.Check
	}
	return nil
}

type ResourceResponse struct {
	Responses []*CheckResourceResponse `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
}

func (m *ResourceResponse) Reset()                    { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string            { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()               {}
func (*ResourceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResourceResponse) GetResponses() []*CheckResourceResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type CheckResourceRequest struct {
	Checks []*Check `protobuf:"bytes,1,rep,name=checks" json:"checks,omitempty"`
}

func (m *CheckResourceRequest) Reset()                    { *m = CheckResourceRequest{} }
func (m *CheckResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckResourceRequest) ProtoMessage()               {}
func (*CheckResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CheckResourceRequest) GetChecks() []*Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

type TestCheckRequest struct {
	MaxHosts int32      `protobuf:"varint,1,opt,name=max_hosts" json:"max_hosts,omitempty"`
	Deadline *Timestamp `protobuf:"bytes,2,opt,name=deadline" json:"deadline,omitempty"`
	Check    *Check     `protobuf:"bytes,3,opt,name=check" json:"check,omitempty"`
}

func (m *TestCheckRequest) Reset()                    { *m = TestCheckRequest{} }
func (m *TestCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*TestCheckRequest) ProtoMessage()               {}
func (*TestCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TestCheckRequest) GetDeadline() *Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *TestCheckRequest) GetCheck() *Check {
	if m != nil {
		return m.Check
	}
	return nil
}

type TestCheckResponse struct {
	Responses []*CheckResponse `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	Error     string           `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *TestCheckResponse) Reset()                    { *m = TestCheckResponse{} }
func (m *TestCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*TestCheckResponse) ProtoMessage()               {}
func (*TestCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TestCheckResponse) GetResponses() []*CheckResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type CheckResponse struct {
	Target   *Target `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Response *Any    `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Error    string  `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Passing  bool    `protobuf:"varint,4,opt,name=passing" json:"passing,omitempty"`
}

func (m *CheckResponse) Reset()                    { *m = CheckResponse{} }
func (m *CheckResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()               {}
func (*CheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CheckResponse) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CheckResponse) GetResponse() *Any {
	if m != nil {
		return m.Response
	}
	return nil
}

type CheckResult struct {
	CheckId    string           `protobuf:"bytes,1,opt,name=check_id" json:"check_id,omitempty"`
	CustomerId string           `protobuf:"bytes,2,opt,name=customer_id" json:"customer_id,omitempty"`
	Timestamp  *Timestamp       `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Passing    bool             `protobuf:"varint,4,opt,name=passing" json:"passing,omitempty"`
	Responses  []*CheckResponse `protobuf:"bytes,5,rep,name=responses" json:"responses,omitempty"`
	Target     *Target          `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
	CheckName  string           `protobuf:"bytes,7,opt,name=check_name" json:"check_name,omitempty"`
}

func (m *CheckResult) Reset()                    { *m = CheckResult{} }
func (m *CheckResult) String() string            { return proto.CompactTextString(m) }
func (*CheckResult) ProtoMessage()               {}
func (*CheckResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CheckResult) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *CheckResult) GetResponses() []*CheckResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *CheckResult) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

type DiscoveryEvent struct {
	CustomerId string     `protobuf:"bytes,1,opt,name=customer_id" json:"customer_id,omitempty"`
	Timestamp  *Timestamp `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Type       string     `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Resource   string     `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
}

func (m *DiscoveryEvent) Reset()                    { *m = DiscoveryEvent{} }
func (m *DiscoveryEvent) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryEvent) ProtoMessage()               {}
func (*DiscoveryEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DiscoveryEvent) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

var E_IsRequired = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         60000,
	Name:          "checker.is_required",
	Tag:           "varint,60000,opt,name=is_required",
}

func init() {
	proto.RegisterType((*Any)(nil), "checker.Any")
	proto.RegisterType((*Timestamp)(nil), "checker.Timestamp")
	proto.RegisterType((*Target)(nil), "checker.Target")
	proto.RegisterType((*Check)(nil), "checker.Check")
	proto.RegisterType((*Header)(nil), "checker.Header")
	proto.RegisterType((*HttpCheck)(nil), "checker.HttpCheck")
	proto.RegisterType((*RDSCheck)(nil), "checker.RDSCheck")
	proto.RegisterType((*Metric)(nil), "checker.Metric")
	proto.RegisterType((*RDSResponse)(nil), "checker.RDSResponse")
	proto.RegisterType((*HttpResponse)(nil), "checker.HttpResponse")
	proto.RegisterType((*CheckResourceResponse)(nil), "checker.CheckResourceResponse")
	proto.RegisterType((*ResourceResponse)(nil), "checker.ResourceResponse")
	proto.RegisterType((*CheckResourceRequest)(nil), "checker.CheckResourceRequest")
	proto.RegisterType((*TestCheckRequest)(nil), "checker.TestCheckRequest")
	proto.RegisterType((*TestCheckResponse)(nil), "checker.TestCheckResponse")
	proto.RegisterType((*CheckResponse)(nil), "checker.CheckResponse")
	proto.RegisterType((*CheckResult)(nil), "checker.CheckResult")
	proto.RegisterType((*DiscoveryEvent)(nil), "checker.DiscoveryEvent")
	proto.RegisterExtension(E_IsRequired)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Checker service

type CheckerClient interface {
	TestCheck(ctx context.Context, in *TestCheckRequest, opts ...grpc.CallOption) (*TestCheckResponse, error)
	CreateCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	RetrieveCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	UpdateCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	DeleteCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
}

type checkerClient struct {
	cc *grpc.ClientConn
}

func NewCheckerClient(cc *grpc.ClientConn) CheckerClient {
	return &checkerClient{cc}
}

func (c *checkerClient) TestCheck(ctx context.Context, in *TestCheckRequest, opts ...grpc.CallOption) (*TestCheckResponse, error) {
	out := new(TestCheckResponse)
	err := grpc.Invoke(ctx, "/checker.Checker/TestCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) CreateCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := grpc.Invoke(ctx, "/checker.Checker/CreateCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) RetrieveCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := grpc.Invoke(ctx, "/checker.Checker/RetrieveCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) UpdateCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := grpc.Invoke(ctx, "/checker.Checker/UpdateCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) DeleteCheck(ctx context.Context, in *CheckResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := grpc.Invoke(ctx, "/checker.Checker/DeleteCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Checker service

type CheckerServer interface {
	TestCheck(context.Context, *TestCheckRequest) (*TestCheckResponse, error)
	CreateCheck(context.Context, *CheckResourceRequest) (*ResourceResponse, error)
	RetrieveCheck(context.Context, *CheckResourceRequest) (*ResourceResponse, error)
	UpdateCheck(context.Context, *CheckResourceRequest) (*ResourceResponse, error)
	DeleteCheck(context.Context, *CheckResourceRequest) (*ResourceResponse, error)
}

func RegisterCheckerServer(s *grpc.Server, srv CheckerServer) {
	s.RegisterService(&_Checker_serviceDesc, srv)
}

func _Checker_TestCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TestCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CheckerServer).TestCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Checker_CreateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CheckResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CheckerServer).CreateCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Checker_RetrieveCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CheckResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CheckerServer).RetrieveCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Checker_UpdateCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CheckResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CheckerServer).UpdateCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Checker_DeleteCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CheckResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CheckerServer).DeleteCheck(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Checker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "checker.Checker",
	HandlerType: (*CheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestCheck",
			Handler:    _Checker_TestCheck_Handler,
		},
		{
			MethodName: "CreateCheck",
			Handler:    _Checker_CreateCheck_Handler,
		},
		{
			MethodName: "RetrieveCheck",
			Handler:    _Checker_RetrieveCheck_Handler,
		},
		{
			MethodName: "UpdateCheck",
			Handler:    _Checker_UpdateCheck_Handler,
		},
		{
			MethodName: "DeleteCheck",
			Handler:    _Checker_DeleteCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 916 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xe3, 0x54,
	0x14, 0x1e, 0xd7, 0xb5, 0x93, 0x9c, 0xa4, 0x9d, 0xe2, 0x32, 0x43, 0x28, 0xea, 0x50, 0x19, 0x06,
	0x01, 0x42, 0xa9, 0xc8, 0x20, 0x16, 0xec, 0xe8, 0x74, 0xd0, 0x20, 0x54, 0x31, 0x94, 0xb2, 0x8e,
	0x1c, 0xfb, 0x90, 0x5a, 0x38, 0xbe, 0xe6, 0xde, 0xeb, 0x0c, 0x91, 0x58, 0xf0, 0x10, 0x6c, 0xd9,
	0xf2, 0x04, 0x3c, 0x06, 0x4b, 0x1e, 0x80, 0x17, 0x41, 0xe2, 0xdc, 0x1f, 0x3b, 0xb1, 0xe3, 0x99,
	0x55, 0x77, 0xcd, 0xb9, 0xe7, 0xe7, 0xfb, 0xbe, 0xf3, 0xe3, 0xc2, 0x71, 0xc1, 0x99, 0x64, 0xe7,
	0xf1, 0x2d, 0xc6, 0x3f, 0x21, 0x9f, 0xe8, 0x5f, 0x41, 0xcf, 0xfe, 0x3c, 0x39, 0x5b, 0x30, 0xb6,
	0xc8, 0xf0, 0x5c, 0x9b, 0xe7, 0xe5, 0x8f, 0xe7, 0x09, 0x8a, 0x98, 0xa7, 0x85, 0x64, 0xd6, 0x35,
	0x9c, 0x82, 0xfb, 0x65, 0xbe, 0x0e, 0x1e, 0x42, 0x5f, 0xae, 0x0b, 0x9c, 0x95, 0x3c, 0x1b, 0x3b,
	0x67, 0xce, 0x87, 0x83, 0x8b, 0xfd, 0xdf, 0xfe, 0x3c, 0x75, 0x82, 0x63, 0xf0, 0x56, 0x51, 0x56,
	0xe2, 0x78, 0x8f, 0x8c, 0x23, 0x63, 0x0c, 0x3f, 0x85, 0xc1, 0x4d, 0xba, 0x44, 0x21, 0xa3, 0x65,
	0x11, 0x3c, 0x80, 0x9e, 0xc0, 0x98, 0xe5, 0x89, 0xd0, 0x81, 0xae, 0x0d, 0x3c, 0x00, 0x2f, 0x8f,
	0x72, 0x26, 0x74, 0xa0, 0x1b, 0x5e, 0x81, 0x7f, 0x13, 0xf1, 0x05, 0xca, 0x60, 0x04, 0xfb, 0x79,
	0xb4, 0x44, 0x53, 0x25, 0x08, 0x60, 0x5f, 0xd5, 0xd5, 0x5e, 0x55, 0xcd, 0x23, 0xd8, 0x4b, 0x93,
	0xb1, 0xbb, 0x65, 0xb9, 0x0f, 0xbd, 0x28, 0x49, 0x38, 0x0a, 0x31, 0xde, 0x57, 0xe6, 0xf0, 0x2f,
	0x07, 0xbc, 0xa7, 0x8a, 0x63, 0x00, 0xda, 0xd9, 0x24, 0x23, 0x12, 0x69, 0x2e, 0x91, 0x13, 0x62,
	0x9d, 0xd0, 0xb3, 0xe1, 0x8f, 0xc1, 0x97, 0xba, 0xb8, 0x4e, 0x3a, 0x9c, 0xde, 0x9f, 0x54, 0x72,
	0x19, 0x4c, 0xd6, 0xed, 0x7d, 0xe8, 0x67, 0x91, 0x90, 0x33, 0x5e, 0xe6, 0xba, 0xcc, 0x70, 0x1a,
	0x6c, 0x1c, 0x6b, 0xbe, 0x1f, 0x00, 0x68, 0xe3, 0x4c, 0x14, 0x18, 0x8f, 0x3d, 0xed, 0x37, 0xaa,
	0xfd, 0x48, 0x4b, 0x9b, 0x2d, 0xb0, 0x3c, 0xfd, 0x0d, 0x8f, 0xf0, 0x13, 0xf0, 0x9f, 0x63, 0x94,
	0x20, 0xaf, 0x5f, 0xb7, 0xb5, 0x3e, 0x04, 0x5f, 0x6b, 0xad, 0x34, 0x73, 0x89, 0xe4, 0x1f, 0x0e,
	0x0c, 0x9e, 0x4b, 0x59, 0x18, 0xa2, 0x3b, 0xba, 0x15, 0x91, 0xbc, 0x6d, 0xe8, 0x46, 0xf4, 0x75,
	0x4f, 0x63, 0x96, 0x35, 0xd4, 0x53, 0xbe, 0x8c, 0x4b, 0xcd, 0xc9, 0xdb, 0xd8, 0x56, 0xc8, 0xe7,
	0x1a, 0x7f, 0xe5, 0x77, 0x06, 0xbd, 0x5b, 0x8d, 0x4e, 0x10, 0x68, 0xb7, 0xa1, 0x93, 0x45, 0x4d,
	0x18, 0xe6, 0x2c, 0x59, 0x8f, 0x7b, 0xba, 0x09, 0xbf, 0x3b, 0xd0, 0xbf, 0xbe, 0xfc, 0xbe, 0x0b,
	0xde, 0x36, 0x94, 0x16, 0xc4, 0x52, 0x20, 0xd7, 0x9e, 0x6e, 0x0b, 0x7a, 0x24, 0xc4, 0x4b, 0xc6,
	0x13, 0xd3, 0xe1, 0x8d, 0x3d, 0x89, 0x64, 0x34, 0x8f, 0x04, 0x36, 0xa0, 0x9e, 0xc0, 0xe8, 0xe7,
	0x12, 0xf9, 0x7a, 0x26, 0x24, 0x4f, 0xf3, 0x45, 0x43, 0xe4, 0x27, 0xe0, 0x5f, 0x21, 0x99, 0xe3,
	0x16, 0xa6, 0x83, 0xed, 0x51, 0x76, 0xd4, 0xa3, 0x8c, 0x16, 0x82, 0x60, 0x28, 0xad, 0xdf, 0x81,
	0x21, 0x51, 0xb9, 0x46, 0x51, 0xb0, 0x5c, 0xa0, 0x7a, 0xe4, 0xec, 0xa5, 0x99, 0xe8, 0x41, 0xf8,
	0x2b, 0x8c, 0x54, 0x1f, 0xb6, 0x5f, 0x63, 0x96, 0x98, 0xbc, 0x5e, 0x2d, 0x8a, 0xe6, 0xb9, 0x2d,
	0xa2, 0xdb, 0x2d, 0x22, 0x79, 0x2c, 0x35, 0x3e, 0x35, 0xcc, 0x4d, 0x8f, 0x0d, 0xee, 0x5b, 0x26,
	0xa4, 0x61, 0x1c, 0x7e, 0x07, 0x0f, 0xb4, 0xc4, 0x54, 0x9e, 0x95, 0x3c, 0xc6, 0x1a, 0xc6, 0xf6,
	0xe8, 0x9f, 0x82, 0xa7, 0x93, 0x68, 0x14, 0xc3, 0xe9, 0x61, 0x9d, 0xd2, 0x74, 0x87, 0xb8, 0x23,
	0xe7, 0x8c, 0x1b, 0xd1, 0xc3, 0x67, 0x70, 0xb4, 0x93, 0x8d, 0x96, 0x9a, 0xdb, 0xbf, 0x15, 0x6f,
	0x05, 0xec, 0x51, 0x33, 0x4b, 0x3b, 0x24, 0xfc, 0x1c, 0xde, 0x6c, 0x3d, 0x50, 0x53, 0x84, 0x0c,
	0x1e, 0x81, 0xaf, 0x03, 0xab, 0x3c, 0x2d, 0x34, 0xa4, 0xe7, 0xd1, 0x0d, 0xf9, 0xd9, 0x58, 0x13,
	0xf3, 0x16, 0x0c, 0x96, 0xd1, 0x2f, 0x33, 0xc5, 0xdb, 0xc8, 0x5e, 0x4d, 0xea, 0xc7, 0x34, 0x02,
	0x24, 0x5c, 0x96, 0xe6, 0x68, 0xc9, 0x75, 0x6c, 0xa5, 0xf5, 0x7d, 0xaf, 0x52, 0xc1, 0xed, 0x52,
	0xc1, 0xce, 0xc7, 0x15, 0xbc, 0xb1, 0x55, 0xdd, 0xb2, 0xff, 0x68, 0x97, 0xfd, 0xc3, 0x1d, 0xf6,
	0xc6, 0xb5, 0xd6, 0x52, 0x37, 0x3c, 0x2c, 0xe0, 0xa0, 0xf9, 0xfe, 0x6e, 0x7d, 0x6d, 0x9c, 0xce,
	0x6b, 0x43, 0xf2, 0xf4, 0xab, 0x5a, 0x96, 0x51, 0xe3, 0x7e, 0xb4, 0x9a, 0xa5, 0x8e, 0x9f, 0xda,
	0x0d, 0x35, 0xe6, 0x6a, 0x35, 0xfa, 0xe1, 0xdf, 0x0e, 0x0c, 0xab, 0x92, 0x65, 0x26, 0xe9, 0x5e,
	0xf6, 0xcd, 0x45, 0xaa, 0xa7, 0xe1, 0x18, 0x86, 0x71, 0x29, 0x24, 0x5b, 0x22, 0x57, 0x46, 0x33,
	0x99, 0x8f, 0x61, 0x20, 0x2b, 0xbd, 0xac, 0x40, 0x5d, 0xf7, 0xad, 0x5d, 0xae, 0x29, 0x8d, 0xf7,
	0x5a, 0x69, 0x36, 0xd4, 0xfd, 0x6e, 0xea, 0x41, 0x75, 0x3c, 0xf5, 0x5e, 0x9a, 0x33, 0x92, 0xc1,
	0xe1, 0x65, 0x2a, 0x62, 0x46, 0xf7, 0x68, 0xfd, 0x6c, 0x85, 0xb9, 0x6c, 0xc3, 0x77, 0x76, 0xe1,
	0xbf, 0x72, 0x10, 0xf4, 0x5a, 0xab, 0x0f, 0x8a, 0xd1, 0xee, 0x48, 0x4b, 0xad, 0x87, 0xd3, 0xdc,
	0x95, 0xe9, 0x7f, 0x7b, 0xd0, 0x7b, 0x6a, 0xa2, 0x82, 0x4b, 0xfa, 0x8e, 0x55, 0x93, 0x10, 0xbc,
	0xbd, 0x49, 0xd6, 0x9a, 0xcd, 0x93, 0x93, 0xae, 0x27, 0xbb, 0x03, 0xf7, 0x82, 0xaf, 0xa9, 0x1b,
	0x1c, 0x23, 0x89, 0x26, 0xcf, 0xe9, 0xab, 0x96, 0xc6, 0xe4, 0xda, 0x94, 0xd9, 0x59, 0xa7, 0x7b,
	0xc1, 0x37, 0x70, 0x70, 0xad, 0x4e, 0x00, 0xae, 0xee, 0x20, 0x19, 0xe1, 0xfa, 0xa1, 0x48, 0xee,
	0x04, 0x17, 0xa5, 0xba, 0xc4, 0x0c, 0xef, 0x20, 0xd5, 0x17, 0x9f, 0xc1, 0x30, 0x15, 0x33, 0x4e,
	0xae, 0x29, 0xc7, 0x84, 0x52, 0x99, 0xff, 0x50, 0x26, 0xd5, 0x7f, 0x28, 0x93, 0xaf, 0x52, 0xcc,
	0x92, 0x6f, 0x0b, 0x99, 0x52, 0xc0, 0xf8, 0xdf, 0x7f, 0x54, 0x1f, 0xfb, 0x17, 0x67, 0x70, 0x18,
	0xb3, 0x09, 0x2b, 0x04, 0x5a, 0xcf, 0x8b, 0xd1, 0x05, 0x7d, 0xaa, 0xc9, 0xe7, 0x85, 0xfa, 0xf5,
	0xc2, 0x99, 0xfb, 0xda, 0xfc, 0xe4, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xbd, 0x9d, 0xfa,
	0x10, 0x09, 0x00, 0x00,
}
